/**
 * Error codes for the Zvid.io library
 * Format: VR_<CATEGORY>_<NUMBER>
 */
export const ERROR_CODES = {
  // Configuration Errors (001-099)
  CONFIG_MISSING_DURATION: 'VR_CONFIG_001',
  CONFIG_INVALID_DIMENSIONS: 'VR_CONFIG_002',
  CONFIG_INVALID_BACKGROUND: 'VR_CONFIG_003',
  CONFIG_MISSING_PROJECT_DATA: 'VR_CONFIG_004',
  CONFIG_INVALID_FRAME_RATE: 'VR_CONFIG_005',
  CONFIG_INVALID_OUTPUT_FORMAT: 'VR_CONFIG_006',

  // Media Processing Errors (100-199)
  MEDIA_FFMPEG_FAILED: 'VR_MEDIA_100',
  MEDIA_INVALID_VIDEO_FORMAT: 'VR_MEDIA_101',
  MEDIA_INVALID_AUDIO_FORMAT: 'VR_MEDIA_102',
  MEDIA_ENCODING_FAILED: 'VR_MEDIA_103',
  MEDIA_FILTER_FAILED: 'VR_MEDIA_104',
  MEDIA_METADATA_EXTRACTION_FAILED: 'VR_MEDIA_105',

  // Resource Errors (200-299)
  RESOURCE_FILE_NOT_FOUND: 'VR_RESOURCE_200',
  RESOURCE_FONT_DOWNLOAD_FAILED: 'VR_RESOURCE_201',
  RESOURCE_IMAGE_LOAD_FAILED: 'VR_RESOURCE_202',
  RESOURCE_NETWORK_ERROR: 'VR_RESOURCE_203',
  RESOURCE_PERMISSION_DENIED: 'VR_RESOURCE_204',
  RESOURCE_DISK_SPACE_INSUFFICIENT: 'VR_RESOURCE_205',

  // Validation Errors (300-399)
  VALIDATION_INVALID_PROJECT_TYPE: 'VR_VALIDATION_300',
  VALIDATION_MISSING_REQUIRED_FIELD: 'VR_VALIDATION_301',
  VALIDATION_INVALID_ITEM_TYPE: 'VR_VALIDATION_302',
  VALIDATION_INVALID_TIME_RANGE: 'VR_VALIDATION_303',
  VALIDATION_INVALID_COORDINATES: 'VR_VALIDATION_304',
  VALIDATION_INVALID_COLOR_FORMAT: 'VR_VALIDATION_305',

  // Rendering Errors (400-499)
  RENDER_CANVAS_FAILED: 'VR_RENDER_400',
  RENDER_PUPPETEER_FAILED: 'VR_RENDER_401',
  RENDER_SVG_CONVERSION_FAILED: 'VR_RENDER_402',
  RENDER_TEXT_GENERATION_FAILED: 'VR_RENDER_403',
  RENDER_IMAGE_PROCESSING_FAILED: 'VR_RENDER_404',
  RENDER_BROWSER_TIMEOUT: 'VR_RENDER_405',

  // Unexpected Errors (500-599)
  UNEXPECTED_UNKNOWN_ERROR: 'VR_UNEXPECTED_500',
  UNEXPECTED_THIRD_PARTY_ERROR: 'VR_UNEXPECTED_501',
  UNEXPECTED_SYSTEM_ERROR: 'VR_UNEXPECTED_502',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Error code categories for easier filtering and handling
 */
export const ERROR_CATEGORIES = {
  CONFIGURATION: 'CONFIG',
  MEDIA_PROCESSING: 'MEDIA',
  RESOURCE: 'RESOURCE',
  VALIDATION: 'VALIDATION',
  RENDERING: 'RENDER',
  UNEXPECTED: 'UNEXPECTED',
} as const;

/**
 * Get error category from error code
 */
export function getErrorCategory(code: ErrorCode): string {
  const category = code.split('_')[1];
  return category || 'UNKNOWN';
}

/**
 * Check if error code belongs to a specific category
 */
export function isErrorCategory(
  code: ErrorCode,
  category: keyof typeof ERROR_CATEGORIES
): boolean {
  return getErrorCategory(code) === ERROR_CATEGORIES[category];
}
